version: 2
updates:
- package-ecosystem: gradle
  target-branch: "development"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: org.mariadb.jdbc:mariadb-java-client
    versions:
    - 2.7.2
  - dependency-name: org.hsqldb:hsqldb
    versions:
    - 2.5.1
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.1
