name: DiscordSRVUtils
depend:
  - DiscordSRV
softdepend:
  - Essentials
  - Advancedban
  - PlaceholderAPI
  - Litebans
  - Libertybans
version: @version@
main: tk.bluetree242.discordsrvutils.DiscordSRVUtils
author: BlueTree242
api-version: 1.13

commands:
  discordsrvutils:
    aliases: [ dsrvu, dsu, du, discordu, srvu ]

permissions:
  discordsrvutils.reload:
    default: false
    description: Allow player to reload the plugin
  discordsrvutils.debug:
    default: false
    description: Allow player to create a debug report
  discordsrvutils.errornotifications:
    default: false
    description: Allow plugin to send errors to this user


