name: DiscordSRVUtils
softdepend:
  - DiscordSRV
  - Essentials
  - Advancedban
version: 1.1.7
main: tech.bedev.discordsrvutils.DiscordSRVUtils
author: Blue_Tree
api-version: 1.13

commands:
  discordsrvutils:
    aliases: [dsrvu, dsu, du, discordu, srvu]
  setlevel:
    aliases: [sl, setl]
    permission: discordsrvutils.setlevel
  addlevels:
    aliases: [al, addl]
    permission: discordsrvutils.addlevels

  removelevels:
    aliases: [rl, removelevels]
    permission: discordsrvutils.removelevels
  setxp:
    aliases: [ sxp, setl ]
    permission: discordsrvutils.setxp
  addxp:
    aliases: [ axp, addxp]
    permission: discordsrvutils.addxp
  removexp:
    aliases: [rxp, removexp]
    permission: discordsrvutils.removexp



