name: DiscordSRVUtils
depend: 
  - DiscordSRV
softdepend:
  - Essentials
  - Advancedban
  - PlaceholderAPI
version: 1.2.0-DEV
main: tk.bluetree242.discordsrvutils.DiscordSRVUtils
author: BlueTree242
api-version: 1.13

commands:
  discordsrvutils:
    aliases: [ dsrvu, dsu, du, discordu, srvu ]


