# This workflow is for master branch and publishing.

name: Build Project & Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"
          java-package: jdk
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-artifacts
          path: "build/libs/*.jar"
      - name: Publish to maven repository
        run: ./gradlew core:publish