# This workflow is for anything not on develop/master/beta branches because jenkins/release workflow already try to build them.

name: Build Project

on:
  push:
    branches:
      - "*"
      - "!develop"
      - '!master'
      - "!beta"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          java-package: jdk
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --no-daemon
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DiscordSRVUtils (jar is in zip)
          path: "build/libs/*.jar"