# This workflow is for anything not on develop branch, because jenkins already try to build that.

name: Build Project

on:
  push:
    branches:
      - "*"
      - "!develop"
      - '!master'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          java-package: jdk
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --no-daemon
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build-artifacts
          path: "build/libs/*.jar"